# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  -   repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.1.0
      hooks:
      - id: check-added-large-files  # prevents giant files from being committed.
        args: ['--maxkb=4096']  # may want to increase
      - id: check-ast  # simply checks whether the files parse as valid python.
      - id: check-json  # checks json files for parseable syntax.
      - id: check-toml  # checks toml files for parseable syntax.
      - id: check-yaml  # checks yaml files for parseable syntax.
      - id: detect-private-key  # detects the presence of private keys.
#      - id: double-quote-string-fixer  # replaces double quoted strings with single quoted strings.
      - id: end-of-file-fixer  # ensures that a file is either empty, or ends with one newline.
      - id: trailing-whitespace  # trims trailing whitespace.

  - repo: https://github.com/PyCQA/isort.git
    rev: '5.12.0'
    hooks:
      - id: isort
        args: ["--profile", "black"]

  - repo: https://github.com/psf/black.git
    rev: '23.7.0'
    hooks:
      -   id: black

  - repo: https://github.com/PyCQA/flake8.git
    rev: '6.1.0'
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-docstrings==1.7.0
