defaults:
  - dataset: gees1_rp
  - _self_

pipeline:
  subset: False
  plot: True
  save: False

# ONLY PUT OTHER STUFF HERE IF YOU WANT TO OVERRRIDE IT THANK YOU
dataset:
  cwd: ${hydra:runtime.cwd}
  datasets_path: ${dataset.cwd}/datasets/
  dataset_name: ${hydra:runtime.choices.dataset}
  outdir: ${dataset.cwd}/outputs/${dataset.dataset_name}/
